name: Generate Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Lua
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks

    - name: Install LDoc dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        sudo luarocks install ldoc

    - name: Generate Documentation
      run: |
        ldoc -c config.ld ${GITHUB_WORKSPACE}/*.lua
        
    - name: Commit Documentation
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: Luca Mauri
        commit_user_email: github@wikitrek.org
        commit_message: 'Update documentation'
        add_options: 'docs/'
