name: Generate Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Lua
      uses: actions/setup-lua@v1
      with:
        lua-version: '5.1'

    - name: Install LuaDoc dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        sudo luarocks install luafilesystem
        sudo luarocks install lualogging

    - name: Generate Documentation
      run: |
        lua luadoc.lua -d docs .
        
    - name: Commit Documentation
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Luca Mauri
        author_email: github@wikitrek.org
        message: 'Update documentation'
        add: 'docs/'
